name: My first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5 #uses because we are making use of an action

            - name: Welcome message
              run: echo "My first Github Actions Job"
            
            - name: List files
              run: ls

            - name: Read file
              run: cat README.md